### ISSUE TITLE
Error while trying to install via pip on Fedora 21 64 bits

### ISSUE THREAD

**Issue by chmeul** [matthew-brett/transforms3d#1]
Hi,
I have issue installing the transforms3d package on my platform (Fedora 21 64 bits)
Here is the result of the command sudo pip install transforms3d:

Downloading/unpacking transforms3d
  Downloading transforms3d-0.2.tar.gz (55kB): 55kB downloaded
  Running setup.py (path:/tmp/pip-build-Pbgfj1/transforms3d/setup.py) egg_info for package transforms3d
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-Pbgfj1/transforms3d/setup.py", line 50, in <module>
        long_description = open('README.rst', 'rt').read(),
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-Pbgfj1/transforms3d/setup.py", line 50, in <module>

    long_description = open('README.rst', 'rt').read(),

IOError: [Errno 2] No such file or directory: 'README.rst'

Any clue?

Regards

**Comment by matthew-brett** [comment]
Oops - yes - that is mistake I made in packaging - thanks very much for pointing that out.  I'll upload a fix soon.

**Comment by matthew-brett** [comment]
Try now?

**Comment by chmeul** [comment]
Ok Fixed!
Installation works, I'll try the routines tomorrow
Thanks a lot
