### ISSUE TITLE
Error in euler2mat in taitbryan.py

### ISSUE THREAD

**Issue by agnarhs** [matthew-brett/transforms3d#11]
Hello,

I have just started using transforms3d and just discovered some strange behaviour of my rotation matrices being returned from euler2mat in taitbryan.py. 

As far as I see the statement return reduce(np.dot, Ms[::-1]) reverses the order of the rotation matrices in Ms and you end up with Rx*Ry*Rz, which is wrong. It should be Rz*Ry*Rx. If the statment is changed to  reduce(np.dot, Ms), everything is in order.

best regards,
Agnar

**Comment by matthew-brett** [comment]
It might be wrong, but I think the code implements z rotation followed by y rotation followed by x rotation, and, this is Rx.dot(Ry.dot(Rx)), with matrix multiplication reading from right to left.

**Comment by matthew-brett** [comment]
(Sorry, just fixed a typo in my reply).

**Comment by agnarhs** [comment]
Hello,

you are absolutely right. My mistake.


regards,
Agnar
