### ISSUE TITLE
transforms3d: object has no attribute 'euler’

### ISSUE THREAD

**Issue by genemiller** [matthew-brett/transforms3d#13]
Attached file shows failure case
[transforms3d.euler.txt](https://github.com/matthew-brett/transforms3d/files/595717/transforms3d.euler.txt)
:
1. Install transforms3d (0.3)
2. Launch python 2.7.11
3. Import transforms3d
4. transforms3d.euler.quat2euler fails with “object has no attribute 'euler’”
5. dir(transforms3d) does not appear to contain ‘euler’ !!
6. Yet help(transforms3d) says it contains ’euler’

**Comment by genemiller** [comment]
Thanks for super fast response!!! Will reinstall and try again.

**Comment by matthew-brett** [comment]
This is because the transforms3d top-level init does not import all its submodules automatically.  I added imports for this - can you confirm that the current code fixes your issue?

**Comment by genemiller** [comment]
Hi mattthew- I am using "pip install" which is probably getting it from https://pypi.python.org/pypi/transforms3d. But this does not seem to contain the fix. I assume I should install from this repository in github. Right?

**Comment by matthew-brett** [comment]
Yes, right.  Try: ```pip install git+https://github.com/matthew-brett/transforms3d```

**Comment by genemiller** [comment]
Yes. It worked.
>>> angles = transforms3d.euler.quat2euler([0.99810947, 0.06146124, 0, 0])
>>> angles
(0.12300000158143692, -0.0, 0.0)
Thanks so much!!

**Comment by yw5aj** [comment]
Hi Matthew,

Thank you for the fix, as well as enhancing this great tool! As of today (6/9/2017) the pypi version still cannot do the following:
```python
In [1]: import transforms3d

In [2]: transforms3d.euler
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-1d30ad26a4a3> in <module>()
----> 1 transforms3d.euler

AttributeError: module 'transforms3d' has no attribute 'euler'
```

Would you mind updating the pypi version when you get a chance, if possible?

Thanks :)

**Comment by matthew-brett** [comment]
Sure - I have made a new release - does it work for you now?

**Comment by mnauf** [comment]
hello @matthew-brett, I am getting the following for doing `pip install git+https://github.com/matthew-brett/transforms3d`:

  ```
Cloning https://github.com/matthew-brett/transforms3d to c:\users\mnauf\appdata\local\temp\pip-req-build-lwlthp
  Running command git clone -q https://github.com/matthew-brett/transforms3d 'c:\users\mnauf\appdata\local\temp\pip-req-build-lwlthp'
    ERROR: Command errored out with exit status 1:
         cwd: c:\users\mnauf\appdata\local\temp\pip-req-build-lwlthp\
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\mnauf\appdata\local\temp\pip-req-build-lwlthp\setup.py", line 8, in <module>
        import versioneer
      File "versioneer.py", line 370
        LONG_VERSION_PY: Dict[str, str] = {}
                       ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by matthew-brett** [comment]
@mnauf - yes - I'm sorry - I accidentally broke Python 2.7 compatibility - because Versioneer, that we use, hasn't had Python 2.7 compatibility for a while.  Is there any chance you can update to Python 3?

**Comment by mnauf** [comment]
@matthew-brett I am not sure if I can. Can you please give me commit till when it worked? I will try to install this by checking out in history

**Comment by mnauf** [comment]
Thanks I did it! `git checkout ccec1878a13a786f7ca3d465a81eb6b865f0ddd6` and then `pip install -e [PATH OF LOCAL PACKAGE]`

**Comment by matthew-brett** [comment]
I guess  you could also use`pip install git+https://github.com/matthew-brett/transforms3d@bb2c0a9`, or even `pip install transforms3d==0.3.1`

**Comment by mnauf** [comment]
I see! Thanks. Really appreciate it
