### ISSUE TITLE
quaternions.rotate_vector seems need normalized quaternion

### ISSUE THREAD

**Issue by zhl355** [matthew-brett/transforms3d#16]
version: transforms3d-0.3.1

q = np.array([1 ,0 ,1, 0])
r = np.array([1,1,1])

R = trans3d.euler.quat2mat(q)

print(np.dot(R,r))

print('Using Trans3d library directly to rotate the vector')
print(trans3d.quaternions.rotate_vector(r,q)) # this q is not normalized

print('Using Trans3d library directly to rotate the vector')
print(trans3d.quaternions.rotate_vector(r,q/quat.norm(q))) # this q  normalized

# very good library 
# it would be better to having rotate_vector function works the same way when quaternion is not # normalized

**Comment by matthew-brett** [comment]
Thanks for the question.   One option would be to follow Matlab, and normalize the quaternion before applying the rotation : https://uk.mathworks.com/help/aerotbx/ug/quatrotate.html . Of course, that would be less efficient for already-normalized quaternions.  How about a keyword argument `normalize=True`, True by default, that would signal whether to apply normalization?

**Comment by zhl355** [comment]
sounds great, thanks for your response!

**Comment by matthew-brett** [comment]
I added an `is_normalized` keyword to the function to at least point this out.  Please reopen if you think this is the wrong option.  I wanted to avoid changing people's output under them, by default.
