### ISSUE TITLE
What is the relation between this package and Christoph Gohlke's code?

### ISSUE THREAD

**Issue by hamogu** [matthew-brett/transforms3d#2]
Hi,

I'm in the process of writing a code where I'll need quite a few 3 d operations (rotation, projection, all this stuff). In order to not reinvent the wheel, I looked round the web and I found both Christoph Gohlke's homepage with his code http://www.lfd.uci.edu/~gohlke/code/transformations.py.html
and your package on github. First, a big thanks to both of you to write this code and make it available.

Now I wonder what the relation between those codes is? You include Christoph's code, but the only way to use is to `import transforms3d._gohlketransforms` (I can do that, but the underscore seems to indicate that that is not the intended way to use it).
I looked through the github repository and e.g. `axangle2mat` is almost identical to Christoph's `rotation_matrix`, yet it is implemented without calling that code.

Now I wonder if I should use your package or Christoph's code. I like the way you format the docstrings in numpydoc format so that sphinx works well on it, I like the tests in a separate directory, I like that transforms3d is on pypi - that's all how I am used to lay out packages and it makes it easy for me to find my way. On the other hand, if I used Christoph's code directly, it would be easy for me to compile his C version if I later find that I need the speed.

Any advice?

**Comment by matthew-brett** [comment]
The relationship between the projects is pretty simple - I copied and reformatted Christoph's code, and wrote some extra code and tests.

I believe Christoph will not likely put up his package separately on pip (Christoph, please correct me if I am wrong), which was part of my motivation for writing this version.

I did think about making Cython versions of the code for speed, but it seemed to me that these operations are generally so small compared to the overhead of a Python function call (into C or Python) that you'd be unlikely to get much of a speed up.  So, it would make sense to call into C transformations from C code, but not - I think - from Python.

Having said that, if you do really hit a bottleneck for which Christoph's C code makes a large difference in speed, I will certainly have a look at porting across the C code or doing a rewrite in Cython.

**Comment by hamogu** [comment]
Thanks for the fast reply. Good to know! I'll use the reformatted version for now and I'll let you know if I run into any trouble.
