### ISSUE TITLE
qnorm returns square norm

### ISSUE THREAD

**Issue by MaximeLemonnier-Leddartech** [matthew-brett/transforms3d#20]
def qnorm(q):
    ''' Return norm of quaternion

    Parameters
    ----------
    q : 4 element sequence
       w, i, j, k of quaternion

    Returns
    -------
    n : scalar
       quaternion norm
    '''
    return np.dot(q, q) <--- wrong! should be np.sqrt(np.dot(q, q))

**Comment by matthew-brett** [comment]
Oops - and I was only testing unit quaterions. Would you mind having a look at https://github.com/matthew-brett/transforms3d/pull/22 ?

**Comment by matthew-brett** [comment]
Closed by #22 - thanks.
