### ISSUE TITLE
Error Building Sphinx-Documentation

### ISSUE THREAD

**Issue by kavonszadkowski** [matthew-brett/transforms3d#28]
Hi Matthew,

I just tried building the documentation running `make html` after installing the dependencies on a recently installed Ubuntu 18.04 and ran into this error:

> Exception occurred:
  File "/home/kavonszadkowski/.local/lib/python2.7/site-packages/numpydoc/docscrape.py", line 422, in _error_location
    raise ValueError(msg)
ValueError: The section Notes appears twice in the docstring of <function mat2quat at 0x7fea4a494758> in /home/kavonszadkowski/.local/lib/python2.7/site-packages/transforms3d/quaternions.py.

Turns out, the section *Notes* **does** appear twice in the docstring of `mat2quat` and merging the two *Notes* blocks fixes the error. Not sure if that is a valid solution or if the error could be solved by changing the settings, so I haven't send a pull request.

**Comment by matthew-brett** [comment]
Yes, sorry - merging the notes is the right solution - would you consider sending a PR?

**Comment by kavonszadkowski** [comment]
Just saw that in the current master branch, it was already fixed by c4e636e7. I installed the package with pip. Not sure what went wrong there.

**Comment by matthew-brett** [comment]
Assuming fixed as above.  Please reopen if I'm wrong.
