### ISSUE TITLE
Overly sensitive mat2axangle

### ISSUE THREAD

**Issue by ikrase** [matthew-brett/transforms3d#3]
It seems like the mat2axangle function is a bit overly sensitive to the eigenvalue not being exactly one. (Within 1e-8)

I keep having trouble with this function failing on all kinds of only slightly inaccurate rotation matrices, even the product of two orthonormalized matrices will often have this closer to 1e-6 which fails. 

Does the tolerance really need to be this high? Could it raise a warning instead?

**Comment by matthew-brett** [comment]
Oh dear - yes - that needs at least to be a parameter that the user can set.

Would you mind reviewing the pull request I just sent to fix this?
