### ISSUE TITLE
euler2mat documentation says it can return 4x4

### ISSUE THREAD

**Issue by FSund** [matthew-brett/transforms3d#34]
According to the `transforms3d.euler.euler2mat` [documentation](https://github.com/matthew-brett/transforms3d/blob/master/transforms3d/euler.py#L181) it returns 

> mat : array-like shape (3, 3) or (4, 4)

But as far as I can see it will [only return 3x3](https://github.com/matthew-brett/transforms3d/blob/master/transforms3d/euler.py#L213-L234). 

```
    M = np.eye(3)
    if repetition:
        M[i, i] = cj
        M[i, j] = sj*si
        M[i, k] = sj*ci
        M[j, i] = sj*sk
        M[j, j] = -cj*ss+cc
        M[j, k] = -cj*cs-sc
        M[k, i] = -sj*ck
        M[k, j] = cj*sc+cs
        M[k, k] = cj*cc-ss
    else:
        M[i, i] = cj*ck
        M[i, j] = sj*sc-cs
        M[i, k] = sj*cc+ss
        M[j, i] = cj*sk
        M[j, j] = sj*ss+cc
        M[j, k] = sj*cs-sc
        M[k, i] = -sj
        M[k, j] = cj*si
        M[k, k] = cj*ci
    return M
```

Is this an error in the docs, or the code, or is there something I'm not seeing?

**Comment by matthew-brett** [comment]
Oops - yes - looks like a documentation error.  Do you have any interest in a little pull request to fix that?

**Comment by FSund** [comment]
Sure!
