### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by kiterunnerly** [matthew-brett/transforms3d#37]
Hello,I'm sure I' ve installed it,I have tried both pip and source installation methods.But here's always the tip"ImportError: No module named 'transforms3d'",can you tell me how to solve this?Thank you and looking forward to your reply！

**Comment by matthew-brett** [comment]
This is almost always because you've installed into a different Python than the one you are importing from.

Try:

```
python -m pip install transforms3d
```

then

```
python
```

and, from the prompt:

```
>>> import transforms3d
```

**Comment by kiterunnerly** [comment]
thank you, I've sorved the problem!
