### ISSUE TITLE
pyvista deprication

### ISSUE THREAD

**Issue by akaszynski** [matthew-brett/transforms3d#40]
Pyvista will be forced to stop using this package unless we can get rid of some of these deprecation warnings and see regular maintenance of this project.  See https://github.com/pyvista/pyvista/issues/1388

If you're unable to continue supporting this, the `pyvista` team would love to adopt this project.  Email me a akascap@gmail.com.

I don't really want to abandon our usage of this package, but if it's not kept up-to-date, we're going to be forced to stop using it.

**Comment by matthew-brett** [comment]
Happy  to fix up the tests and deprecation warnings - is that what you mean?

**Comment by akaszynski** [comment]
> Happy to fix up the tests and deprecation warnings - is that what you mean?

Yes, that would be great!  There's a ton of warnings from `numpy` that need to be fixed (see https://github.com/pyvista/pyvista/issues/1388 for details).
