### ISSUE TITLE
quaternion dual quaternion and other library

### ISSUE THREAD

**Issue by romainVala** [matthew-brett/transforms3d#43]
Hi Matthew, 

Not really an issue, here, but just a curious question :

I wonder if you know 

https://rock-learning.github.io/pytransform3d/index.html

it looks like a lot of same tasks, but I found their euler2matrix functions very clear (regarding the 24 possible conventions)

 but there are also more tools available, like the dual quaternion, that I learned about only recently, I think it is a much more powerfull representation than the affine
( this is for sure important for  interpolation of  transforms, very well know in the game industry )

**Comment by matthew-brett** [comment]
Thanks!   I didn't know it.   Do you mean, you like having the work done by functions with different names like `active_matrix_from_intrinsic_euler_yzy`?

**Comment by romainVala** [comment]
well, it does not make a big difference, although I prefer your way with an extra input parameter axes='sxyz' but I found their construction a bit more understandable ... 

though it is still a nightmare this euler representaion, (especially when I try to compare a affine registration from fsl to one from itk ... so much way to make it wrong)

I am still not sure, if the dual quaternion will make a real difference for this, but the claim to be coordinate free makes me think it could be better ...
