### ISSUE TITLE
undrestanding itk convention

### ISSUE THREAD

**Issue by romainVala** [matthew-brett/transforms3d#44]
Hi, 

sorry if it is not the right place to ask (may be I should use nipy discourse ?)

I try to understand, and to repreduce with your euler2mat function the 2 different ITK convention to build the rotation matrix from euler angle

As explain here: https://discourse.itk.org/t/understanding-sitk-euler3dtransform-convention/4422/2 

with ITK "ZYX" convention, I can get the same rotation matrix with 
euler2mat(theta_x, theta_y, theta_z, axes='sxyz')

But in order to get the same with IRK "ZXY" I need to swap x and y

I first though it will be: 
`euler2mat(theta_x, theta_y, theta_z, axes='syxz')`

but I need to swap the input angle too, which I find weird
`euler2mat(theta_y, theta_x, theta_z, axes='syxz')`

does it make sense why this second solution is the one to choose ?

**Comment by matthew-brett** [comment]
Well - consider the axes `syxy`.   What should the arguments be there?   It no longer makes sense to map them to x, y, and z...

**Comment by romainVala** [comment]
ok I think I see your point,
but I am still confuse, because from simpleitk point of view, I specify the euler angle always with the same order (for the both conventions) and they are related to physical axes x,y,z, it is just the multiplication order that changes

So in itk "world" if I specify the eurler angle [0 10 0 ] I get the same rotation matrix for both conventions 

whereas with euler2mat, I need to change the euler definition ... [0 10 0] for sxyz but [10 0 0] for syxz

it gives me a working solution so that is probably fine, I just wonder if this swap comes from a bad definition of euler angle from itk or not ...

**Comment by matthew-brett** [comment]
How does ITK deal with the `syxy` convention?

**Comment by romainVala** [comment]
the don't, they just have 2 possible conventions that they note ZXY (the default) and 'ZYX' and it is hard to find information on it, but the link I post explain how they interpret it, 

(note that their notation is not clear, since itk "ZXY" convention map to 'sxyz'

I think they rely on an unusual euler convention (which is kind of weird, for a so famous tools no ?), but I would like you confirm ...

**Comment by matthew-brett** [comment]
Er - well - yes - if you don't have to deal with axes that are not one of
xyz or zyx, then you can go for their API - but otherwise, it doesn't make
any sense for the arguments to be in x, y, z order...

It does seem odd to restrict the axes in that way.  But I guess once you've
made the API decision, the restriction follows.

**Comment by romainVala** [comment]
when one say that there is 24 euler possible conventions, then I guess we have one more here ...

thanks for your time

**Comment by matthew-brett** [comment]
I think we've agreed here?  Closing on that assumption, but please re-open if I'm wrong.
