### ISSUE TITLE
Incorrect composition of ZS

### ISSUE THREAD

**Issue by dwml** [matthew-brett/transforms3d#51]
https://github.com/matthew-brett/transforms3d/blob/b02ea8254b623cd2780c5229a9e6f3ea2ac845dd/transforms3d/affines.py#L302

this line should be
`ZS = Z.T * Smat`

**Comment by matthew-brett** [comment]
What are you thinking of for `Z`?   I mean, what shape?

**Comment by dwml** [comment]
Upon review it seems to be a rounding issue in my code that has nothing to do with this package.
