### ISSUE TITLE
Publish wheels?

### ISSUE THREAD

**Issue by effigies** [matthew-brett/transforms3d#61]
When installing something with `pip install --prefer-binary`, transforms3d will install [0.2.1](https://pypi.org/project/transforms3d/0.2.1/#files) if it is in the dependency graph. Would it be possible to start publishing wheels again?

**Comment by matthew-brett** [comment]
Aha - yes - that's an inconvenience.    Wilco.

**Comment by matthew-brett** [comment]
Uploaded - I think.

**Comment by effigies** [comment]
Looks like it. Thanks!
