### ISSUE TITLE
No module named 'transforms3d'

### ISSUE THREAD

**Issue by peng1999** [matthew-brett/transforms3d#67]
The import error happens only in the latest 0.4.2 version.

Steps to reproduce:

```
docker run -it --rm ros:humble

apt update && apt install python3-pip
python3 -m pip install transforms3d==0.4.2
python3 -c 'import transforms3d'
```

It gives error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'transforms3d'
```

**Comment by Danilrivero** [comment]
Can confirm the behaviour. The latest update 0.4.2 on PyPI breaks CI by filling a rosdep dependency with the pip installation option that does not find the module.

`   Installing the transforms3d library by hand required. 
Please run sudo pip3 install transforms3d
`

It would be also interesting to update the packages for **apt** to the latest version (taking into account this issue in 0.4.2).

**Comment by matthew-brett** [comment]
Yes, I see it.  There is something very odd going on with the Ubuntu install such that it does not install the transforms3d directory from the source archive.   The difference between 0.4.1 and 0.4.2 - I think - is that 0.4.1 had a wheel.   I've uploaded a wheel now, to PyPI - it seems to work - can you confirm?

**Comment by matthew-brett** [comment]
Ah no - I stand corrected - it's not the presence of a wheel.  I think the wheel does fix the pip install for 0.4.2, but disabling the wheel does not break the pip install for 0.4.1, whereas it does break the pip install for 0.4.2 - test:

```bash
pip install --no-cache --no-binary transforms3d transforms3d==0.4.1
python3 -c 'import transforms3d'  # Works fine.
pip install --no-cache --no-binary transforms3d transforms3d==0.4.2
python3 -c 'import transforms3d'  # gives ModuleNotFoundError
```

On further investigation, it seems that installation from the source archive will fail for 0.4.2 with pip<22.3 - and the default on the given image is 22.0.2 .   So I suspect that pip<22.3 isn't reading the `pyproject.toml` file correctly.

**Comment by Danilrivero** [comment]
> Yes, I see it. There is something very odd going on with the Ubuntu install such that it does not install the transforms3d directory from the source archive. The difference between 0.4.1 and 0.4.2 - I think - is that 0.4.1 had a wheel. I've uploaded a wheel now, to PyPI - it seems to work - can you confirm?

Hello @matthew-brett, thanks for your swift response on this matter. I can confirm this does indeed fix the problem. My CI is passing now. As per the reason of this, I am using **pip 22.0.2** which could lead to the issue you mention.

**Comment by peng1999** [comment]
Confirmed that this issue has been resolved. Closing it now.
